### PR TITLE
fix: multiline blade component attribute indents forever

### LINKED ISSUE #541: Blade Component attribute indents on save
## Context (Environment)

Identical to https://github.com/shufo/blade-formatter/issues/333 - now with Laravel Component attributes.

## Current Behavior

```
<x-forms.radios
    legend="Meeting Schedule"
    name="meeting_type"
    value="single"
    v-model="form.meeting_type"
    :inline="true"
    :options="[
        'single' => ['label' => 'Default'],
        'series' => ['label' => 'Recurring meeting'],
        'scheduler' => ['label' => 'Find a meeting date'],
]" />
```

Will indent to:

```
<x-forms.radios
    legend="Meeting Schedule"
    name="meeting_type"
    value="single"
    v-model="form.meeting_type"
    :inline="true"
    :options="[
                'single' => ['label' => 'Default'],
                'series' => ['label' => 'Recurring meeting'],
                'scheduler' => ['label' => 'Find a meeting date'],
        ]" />
```

## Expected Behavior

Don't indent on save

## Possible Solution

Port fix for https://github.com/shufo/blade-formatter/issues/333

## Steps to Reproduce

https://user-images.githubusercontent.com/347482/160688772-4be14887-9525-4b64-8854-1580acd66cf8.mov

### PR DESCRIPTION
**Pull request by shufo**
- fix: 🐛 blade component attribute indents forever
- test: 💍 add test for component attribute

## Description

This PR fixes #541

## Related Issue

- #541

## Motivation and Context

Blade component with attribute should keep its indent position.

e.g.

```blade
    <x-forms.radios legend="Meeting Schedule" name="meeting_type" value="single" v-model="form.meeting_type"
        :inline="true" :options="[
            'single' => ['label' => 'Default'],
            'series' => ['label' => 'Recurring meeting'],
            'scheduler' => ['label' => 'Find a meeting date'],
        ]" />
```

## How Has This Been Tested?

see tests

### CODE REVIEW

**Comment by dianfishekqi** [comment]
Hello @shufo,
This brakes with attributes containing javascript

**Comment by shufo** [comment]
Hi @dianfishekqi. Thanks for letting me know.

Can you post example code?

**Comment by dianfishekqi** [comment]
Hello @shufo,
```blade
   <tbody x-data
                   class="divide-y divide-gray-200 bg-gray-50">
                <template x-for="shipment in in_progress"
                          :key="shipment.id">
```

Screen Shot 2022-04-11 at 22 20 00

**Comment by shufo** [comment]
@dianfishekqi 
This regression bug fixed at https://github.com/shufo/blade-formatter/releases/tag/v1.23.2

**Pull request merged**
